arr1 = new Array("purple", "green", "yellow");
arr2 = ["black", "orange", "pink"];
console.log(arr1);
console.log(arr2);
arr3 = new Array(10);
arr4 = [10];
console.log(arr3);
console.log(arr4);
let arr = ["hi there", 5, true];
console.log(typeof arr[0]);
console.log(typeof arr[1]);
console.log(typeof arr[2]);
// const arr = ["hi there"];
// arr[0] = "new value";
console.log(arr[0]);
cars = ["Toyota", "Renault", "Volkswagen"];
console.log(cars[0]);
console.log(cars[3]);
console.log(cars[-1]);
cars[0] = "Tesla";
console.log(cars[0]);
console.log(cars);
cars[3] = "Kia";
cars[-1] = "Flat";
console.log(cars[3]);
console.log(cars[-1]);
groceries = ["Cereal", "Milk", "Apple", "Fruits", "Oats"];
console.log(groceries[0]);
console.log(groceries[3]);
groceries[3] = "Skincare";
console.log(groceries[3]);
console.log(groceries);
colors = ["black", "orange", "pink"];
booleans = [true, false, false, true];
emptyArray = [];
console.log("Length of colors:", colors.length);
console.log("Length of booleans:", booleans.length);
console.log("Length of empty array:", emptyArray.length);
lastElement = colors[colors.length - 1];
console.log(lastElement);
numbers = [12, 24, 36];
numbers[5] = 48;
console.log(numbers.length);
console.log("numbers", numbers);
shoppinglist = ["Milk", "Bread", "Apples"];
console.log(shoppinglist.length);
shoppinglist[1] = "Bananas";
console.log(shoppinglist[1]);
console.log(shoppinglist);
favoriteFruits = ["grapefruit", "orange", "lemon"];
favoriteFruits.push("tangerine");
console.log(favoriteFruits);
console.log(favoriteFruits.length);
let lengthOfFavoriteFruits = favoriteFruits.push("lime");
console.log(favoriteFruits);
console.log(favoriteFruits.length);
favoriteFruits.pop();
console.log(favoriteFruits.pop());
let arrOfShapes = ["circle", "triangle", "rectangle", "pentagon"];
arrOfShapes.splice(2, 0, "square", "trapezoid");
console.log(arrOfShapes);
arrOfShapes.splice(2, 12, "square", "trapezoid");
console.log(arrOfShapes);
let arr5 = [1, 2, 3];
let arr6 = [4, 5, 6];
let arr7 = arr5.concat(arr6);
console.log(arr7);
let arr8 = arr7.concat(7, 8, 9);
console.log(arr8);
arr8.pop();
console.log(arr8.pop());
arr8.shift();
console.log(arr8.shift());
arr8.splice(1, 3);
console.log(arr8.splice(1, 3));
delete arr8[0];
console.log(delete arr8[0]);
arr8 = [2, 6, 7, 8];
let findIndex = arr8.indexOf(6);
let findIndex2 = arr8.indexOf(10);
console.log(findIndex, findIndex2);
let findIndex3 = arr8.indexOf(6, 2);
console.log(findIndex3);
let animals = ["dog", "horse", "cat", "platypus", "dog"];
let lastDog = animals.lastIndexOf("dog");
console.log(lastDog);
let names = ["James", "Alicia", "Fatiha", "Maria", "Bert"];
names.sort();
console.log(names);
names.reverse();
console.log(names);
let ages = [18, 72, 33, 56, 40];
ages.sort();
console.log(ages);
groceriesList = ["Milk", "Bread", "Apples"];
console.log(groceriesList);
(groceriesList[1] = "Bananas"), "Eggs";
console.log(groceriesList[1]);
console.log(groceriesList);
let someValues1 = [1, 2, 3];
let someValues2 = [4, 5, 6];
let someValues3 = [7, 8, 9];
let arrOfArrays = [someValues1, someValues2, someValues3];
console.log(arrOfArrays);
let arrOfArrays2 = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
];
console.log(arrOfArrays2);
let value1 = arrOfArrays[0][1];
console.log(value1);
let value2 = arrOfArrays[2][2];
console.log(value2);
arrOfArraysOfArrays = [arrOfArrays, arrOfArrays, arrOfArrays];
console.log(arrOfArraysOfArrays);
let middleValue = arrOfArraysOfArrays[1][1][1];
console.log(middleValue);
let newValues = [1, 2, 3];
let arrOfArrays3 = [newValues, newValues, newValues];
console.log(newValues);
console.log(arrOfArrays3);
let value3 = arrOfArrays3[1][1];
console.log(value3);
