let nr = 2;
console.log(++nr);
let nr2 = 2;
console.log(nr2++);
console.log(nr2);
let valueOfA = prompt("What is the value of A?");
console.log("The value of A=10");
let valueOfB = prompt("what is the value of B?");
console.log("The value of B=6");
let A = 10;
let B = 6;
let result1 = A ** 2;
let result2 = B ** 2;
console.log(result1, result2);
console.log(result1 + result2);
console.log(Math.sqrt(result1 + result2));
let x = 3;
console.log((x += 5));
console.log((x -= 3));
console.log((x *= 6));
console.log((x **= 2));
console.log((x %= 3));
let a = 4;
let b = 5;
let c = 6;
console.log(b + a);
console.log(c / a);
let result3 = 6 % 5;
console.log(result3);
let d = 5;
let e = "5";
console.log(d == e);
console.log(d === e);
let valueInMiles = 5;
convertMilesToKm = valueInMiles * 1.63904;
console.log(convertMilesToKm);
console.log("The distance of 8.1952kms is equal to 5 miles");
let heightInInches = 187;
let weightInPounds = 80;
heightInCentimeters = heightInInches * 2.54;
weightInKilos = weightInPounds / 2.2046;
console.log(heightInCentimeters, weightInKilos);
heightInMeters = heightInCentimeters / 100;
console.log(heightInMeters);
console.log((BMI = weightInKilos / heightInMeters ** 2));
const f = "5";
console.log(f);
let g = "Hello";
g = "world";
console.log(g);
let h = "Hello";
h = prompt("world");
console.log(h);
let j = 5;
let k = 70;
let l = "5";
++k;
console.log(k);
let result4 = 3 + (4 * 2) / 8;
console.log(result4);
let firstNum = 5;
let secondNum = 10;
firstNum++;
secondNum--;
let total = ++firstNum + secondNum;
console.log(total);
let total2 = 500 + 100 / 5 + total--;
console.log(total2);
