console.log("My name is Esther Akinbile");
/*The code snippet written above is just to let
people kmow the name of this frontend dev*/
let firstname = "Maria";
firstname = "Jacky";
let language = "JavaScript";
let message = `Let's learn ${language}`;
console.log(message);
let str = 'Hello, what\'s your name? Is it "Mike"?';
console.log(str);
let str1 = 'Hello, what\'s your name? Is it "Mike"?';
console.log(str1);
let str2 = "New \nline.";
let str3 = "I'm containing a backslash: \\!";
console.log(str2);
console.log(str3);
let intNr = 1;
let octNr = 0o10;
let intNr2 = 3456;
let intNr3 = -111;
let BigNr = 9007199254740929n;
// let result=intNr+BigNr;
let bool1 = false;
let bool2 = true;
let str4 = "JavaScript is fun!";
let str5 = "JavaScript is fun!";
console.log("These two strings are the same:", str4 === str5);
let sym1 = Symbol("JavaScript is fun!");
let sym2 = Symbol("JavaScript is fun!");
console.log("These two symbols are the same:", sym1 === sym2);
let unassigned;
console.log(unassigned);
let terribleThingToDo = undefined;
let lastName;
console.log("Same Undefined:", lastName === terribleThingToDo);
let betterOption = null;
console.log("Same null:", lastName === betterOption);
testVariable = 1;
variableTypeTest1 = typeof testVariable;
variableTypeTest2 = typeof testVariable;
console.log(variableTypeTest1);
console.log(variableTypeTest2);
let str6 = "Hello";
let nr = 7;
let BigNr1 = 12345678901234n;
let bool = true;
let sym = Symbol("unique");
let undef = undefined;
let unknown = null;
console.log("str", typeof str6);
console.log("nr", typeof nr);
console.log("bigNr", typeof bigNr1);
console.log("bool", typeof bool);
console.log("sym", typeof sym);
console.log("undef", typeof undef);
console.log("unknown", typeof unknown);
let nr1 = 2;
let nr2 = "2";
console.log(nr1 * nr2);
let nr3 = 2;
let nr4 = "2";
console.log(nr3 + nr4);
let nrToStr = 6;
nrToStr = String(nrToStr);
console.log(nrToStr, typeof nrToStr);
let strToNr2 = "hello";
strToNr2 = Number(strToNr2);
console.log(strToNr2, typeof strToNr2);
let nr5 = 2;
let nr6 = "2";
console.log(nr5 + Number(nr6));
let str7 = "Laurence";
let str8 = "Svekis";
let val1 = undefined;
let val2 = null;
let myNum = 1000;
console.log("str", typeof str7);
console.log("str", typeof str8);
console.log("val", typeof val1);
console.log("val", typeof val2);
let nr7 = 12;
let nr8 = 14;
console.log(nr7 + nr8);
let str9 = "Hello ";
let str10 = "addition";
console.log(str9 + str10);
let name = " Hello, my name is Ayomide, ";
let newLine = "New \nline.";
let age = "I am 20 years old, ";
// let bool3 = false;
// let bool4 = true;
let str11 = "And i can code Javascript: true";
let str12 = "And I can't code Javascript: false";
console.log(name + age + str12);
let nr9 = 20;
let nr10 = 4;
let str13 = "Hi";
let nr11 = 3;
let result1 = nr9 - nr10;
let result2 = str13 - nr11;
console.log(result1, result2);
let nr12 = 2;
let nr13 = 3;
let result3 = nr12 ** nr13;
console.log(result3);
let nr14 = 10;
let nr15 = 3;
let result4 = nr14 % nr15;
console.log(`${nr14} % ${nr15} = ${result4}`);
let nr16 = 4;
nr16++;
console.log(nr16);
let nr17 = 2;
console.log(nr17++);
console.log(nr17);
let nr18 = 2;
console.log(++nr18);
let nr19 = 2;
console.log(nr19++);
console.log(nr19);
// let age1;
// console.log(age1);
